version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - network1
    environment:
      - MATCH_STORE_REDIS_URL=redis://matchstore:6379
  matchstore:
    image: redis:6.0.8
    networks:
      - network1
networks:
  network1:
