[build]
  base = "public"
  command = "cp config/settings.example.json config/settings.json && npm install && npm run build && cp -R assets dist"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://35.238.71.180:3000/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "http://35.238.71.180:4000/:splat"
  status = 200