---
kind: Service
apiVersion: v1
metadata:
  name: api
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"socket":"api-socket"}}'
spec:
  selector: # Select pods that will work under this service
    service: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      name: http
    - protocol: TCP
      port: 4000
      name: socket
