---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: api-store-redis
spec:
  serviceName: api-store-redis
  replicas: 1
  selector: # Select pods that will work under this StatefulSet
    matchLabels:
      service: api-store-redis
  template:
    metadata:
      labels: # Pods labels
        service: api-store-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis
          image: redis:6.0.8
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 50Mi