name: CI

on:
  push:
    branches: [ master ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Prepare dependencies
        run: |
          npm install --prefix server
          docker-compose up -d matchstore

      - name: Test
        run: npm run test --prefix server

      - name: Cleanup
        run: docker-compose down

  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "301.0.0"
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Auth docker and kubectl with gcloud
        env:
          GCP_PROJECT: ${{secrets.GCP_PROJECT}}
          GKE_CLUSTER: ${{secrets.GKE_CLUSTER}}
        run: |
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials --region us-central1-a --project $GCP_PROJECT $GKE_CLUSTER
          kubectl config set-context $(kubectl config current-context) --namespace=default

      - name: Build docker images
        env:
          GCP_PROJECT: ${{secrets.GCP_PROJECT}}
        run: |
          COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          BRANCH=${GITHUB_REF##*/}
          IMAGE=us.gcr.io/$GCP_PROJECT/api:$BRANCH-$COMMIT_HASH
          sed -i -e 's|_IMAGE_|'"$IMAGE"'|g;' infra/Deployment.yml
          docker build -t $IMAGE .
          docker push $IMAGE
          
      - name: Deploy
        run: |
          kubectl apply -f infra/
          kubectl rollout status -f infra/Deployment.yml
          kubectl rollout status -f infra/StatefulSet-store-redis.yml

  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: |
          cp public/config/settings.example.json public/config/settings.json
          npm install --prefix public
          npm link webpack
          npm link webpack-merge
      
          
      - name: Build
        run: npm run build --prefix public

   
