name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build the stack
        run: docker-compose up -d matchstore

      - name: Install
        run: npm install --prefix server

      - name: Test
        run: npm run test --prefix server
    
  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: | 
          npm install --prefix server
          npm link webpack
          npm link webpack-merge
      
          
      - name: Build
        run: npm run build --prefix public

   
